
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from cgitb import text
from email.mime import image
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from turtle import width


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1000x750")
window.configure(bg = "#FFFFFF")
window.title("Music Player")
window.iconbitmap(".image\gura.ico")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 750,
    width = 1000,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    500.0,
    375.0,
    image=image_image_1
)

canvas.place(x = 0, y = 0)
image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_1 = canvas.create_image(
    800.0,
    195.0,
    image=image_image_2
)

canvas.create_text(
    675.0,
    382.0,
    anchor="nw",
    text="05 - Lullaby",
    fill="#FFFFFF",
    font=("Inter", 30 * -1)
)

canvas.create_text(
    675.0,
    429.4,
    anchor="nw",
    text="Snail’s House",
    fill="#FFFFFF",
    font=("Inter", 30 * -1)
)

canvas.create_text(
    675.0,
    476.2,
    anchor="nw",
    text="Ordinary Songs 3",
    fill="#FFFFFF",
    font=("Inter", 30 * -1)
)

canvas.create_text(
    675.0,
    523.1,
    anchor="nw",
    text="2017",
    fill="#FFFFFF",
    font=("Inter", 30 * -1)
)

canvas.place(x = 0, y = 0)
bar_image_1 = PhotoImage(
    file=relative_to_assets("bar_1.png"))
image_1 = canvas.create_image(
    800.0,
    577.8,
    image=bar_image_1
)

canvas.place(x = 0, y = 0)
bar_image_2 = PhotoImage(
    file=relative_to_assets("bar_2.png"))
image_1 = canvas.create_image(
    800.0,
    577.8,
    image=bar_image_2,
)

canvas.place(x = 0, y = 0)
dot_image_1 = PhotoImage(
    file=relative_to_assets("dot_1.png"))
dot_1 = Button(
    image=dot_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("dot_1 clicked"),
    relief="flat"
)
dot_1.place(
    x=786.5,
    y=564.3,
    width=27.0,
    height=27.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="sunken"
)
button_2.place(
    x=540.0,
    y=37.0,
    width=85.0,
    height=45.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="sunken"
)
button_1.place(
    x=500.0,
    y=37.0,
    width=85.0,
    height=45.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_1 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="sunken"
)
button_1.place(
    x=20.0,
    y=37.0,
    width=55.0,
    height=45.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    285.0,
    57.0,
    image=entry_image_1
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    320.0,
    404.6,
    image=entry_image_2
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=745.0,
    y=615.0,
    width=25.0,
    height=25.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=775,
    y=601.9,
    width=50.0,
    height=50.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=830.0,
    y=615.0,
    width=25.0,
    height=25.0
)
window.resizable(False, False)
window.mainloop()
