# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from cgitb import text
from email.mime import image
from pathlib import Path
from PIL import Image, ImageTk, ImageDraw, ImageFont, ImageOps
from matplotlib import image
import subprocess
from metadata import AudioMetadata

import io
from tinytag import TinyTag

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from turtle import width
import tkinter as tk

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def open_py_file():
    subprocess.call(["python", "build_demo1/metadata.py"])

open_py_file()

window = tk.Tk()

window.geometry('800x600')
window.configure(bg = "#FFFFFF")
window.title("Music Player")
window.iconbitmap(".image\gura.ico")


canvas = tk.Canvas(
    window,
    bg = "#FFFFFF",
    height = 800,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

#FONDO
canvas.place(x = 0, y = 0)
image_image_1 = ImageTk.PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    400.0,
    300.0,
    image=image_image_1
)

#PORTADA
canvas.place(x = 0, y = 0)
image_image_2 = (Image.open('build_demo1/assets/cover_rounded.png'))
resize_image_image_2 = image_image_2.resize((200,200))
image_image_2 = ImageTk.PhotoImage(resize_image_image_2)
image_1 = canvas.create_image(
    640.0,
    156.0,
    image=image_image_2
)

#NOMBRE
canvas.create_text(
    540.0,
    296.7,
    anchor="nw",
    text=AudioMetadata.title,
    fill="#FFFFFF",
    font=("Inter", 18)
)

#ARTISTA
canvas.create_text(
    540.0,
    334.6,
    anchor="nw",
    text=AudioMetadata.artist,
    fill="#FFFFFF",
    font=("Inter", 18)
)

#ALBUM
canvas.create_text(
    540.0,
    372.1,
    anchor="nw",
    text=AudioMetadata.album,
    fill="#FFFFFF",
    font=("Inter", 18)
)

#AÑO
canvas.create_text(
    540.0,
    407.9,
    anchor="nw",
    text=AudioMetadata.year,
    fill="#FFFFFF",
    font=("Inter", 18)
)

#BARRA_REPRODUCCION
canvas.place(x = 0, y = 0)
bar_image_1 = ImageTk.PhotoImage(file=relative_to_assets("bar_1.png"))
image_1 = canvas.create_image(640.0, 462.2, image=bar_image_1)

canvas.place(x = 0, y = 0)
bar_image_2 = ImageTk.PhotoImage(file=relative_to_assets("bar_2.png"))
image_1 = canvas.create_image(640.0, 462.2, image=bar_image_2)

dot_image_2 = ImageTk.PhotoImage(file=relative_to_assets("dot_1.png"))
dot_1 = canvas.create_image(561.6, 462.2, image=dot_image_2, tag='Dot_1')
canvas.tag_bind(dot_1, "<Button>", lambda event: print('Dot_1 clicked'))

#YOUTUBE
button_image_1 = ImageTk.PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = canvas.create_image(448, 45.6, image=button_image_1, tag='Button_1')
canvas.tag_bind(button_1, "<Button>", lambda event: print('Button_1 clicked'))

#SPOTIFY
button_image_2 = ImageTk.PhotoImage(file=relative_to_assets("button_2.png"))
button_2 = canvas.create_image(480, 45.6, image=button_image_2, tag='Button_2')
canvas.tag_bind(button_2, "<Button>", lambda event: print('Button_2 clicked'))

#BARRA BUSQUEDA
entry_image_1 = ImageTk.PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(224, 45.6, image=entry_image_1)
entry_1 = Entry(
    bd=0,
    bg="#E0E0E3",
    highlightthickness=0,
    cursor="xterm",
    justify="left",
    font=("UD Digi Kyokasho NK-R", 24 * -1)
)
entry_1.place(
    x=50.0,
    y=31.5,
    width=368,
    height=30.0
)

#BUSQUEDA
button_image_7 = ImageTk.PhotoImage(file=relative_to_assets("button_7.png"))
button_7 = canvas.create_image(32, 45.6, image=button_image_7, tag='Button_7')
canvas.tag_bind(button_7, "<Button>", lambda event: print('Button_7 clicked'))

#CANCIONES
entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(256, 323.6, image=entry_image_2)

#ANTERIOR
button_image_3 = ImageTk.PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = canvas.create_image(604.5, 493.5, image=button_image_3, tag='Button_3')
canvas.tag_bind(button_3, "<Button>", lambda event: print('Button_3 clicked'))

#PAUSA
button_image_4 = ImageTk.PhotoImage(file=relative_to_assets("button_4.png"))
button_4 = canvas.create_image(640, 493.5, image=button_image_4, tag='Button_4')
canvas.tag_bind(button_4, "<Button>", lambda event: print('Button_4 clicked'))

#SIGUIENTE
button_image_6 = ImageTk.PhotoImage(file=relative_to_assets("button_6.png"))
button_6 = canvas.create_image(675.5, 493.5, image=button_image_6, tag='Button_6')
canvas.tag_bind(button_6, "<Button>", lambda event: print('Button_6 clicked'))

window.resizable(False, False)
window.mainloop()
